spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_learning?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:com/condemn/**/xml/*Mapper.xml
  #自动驼峰映射
  configuration:
    map-underscore-to-camel-case: true