server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_learning?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: redisson


mybatis-plus:
  mapper-locations:
    - classpath*:com/codeman/**/xml/*Mapper.xml
    - classpath:mapper/*.xml
    - classpath:dao/*.xml

