spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_authorization?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  security:
    user:
      name: root
      password: root


mybatis-plus:
  mapper-locations: classpath*:com/codeman/**/xml/*Mapper.xml